# Generated by Django 6.0.6 on 2026-06-29 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(choices=[('tienda', 'Tienda'), ('vendedor', 'Vendedor')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20)),
                ('total', models.FloatField(default=0.0)),
                ('comision_plataforma', models.FloatField(default=0.0)),
                ('cobro_confirmado', models.IntegerField(default=0)),
                ('nota_voz_url', models.TextField(blank=True, null=True)),
                ('lat_entrega', models.FloatField(blank=True, null=True)),
                ('lng_entrega', models.FloatField(blank=True, null=True)),
                ('telefono_contacto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('logo', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('direccion_texto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mayorista',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appDjango.usuario')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Bebidas', 'Bebidas'), ('Abarrotes', 'Abarrotes'), ('Lacteos', 'Lacteos'), ('Limpieza', 'Limpieza'), ('Otro', 'Otro')], max_length=50)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('activo', 'Activo'), ('suspendido', 'Suspendido')], default='pendiente_pago', max_length=20)),
                ('plan', models.CharField(choices=[('suscripcion', 'Suscripcion'), ('comision', 'Comision'), ('mixto', 'Mixto')], default='suscripcion', max_length=20)),
                ('tarifa_anual', models.FloatField(default=0.0)),
                ('porcentaje_comision', models.FloatField(default=0.0)),
                ('fecha_vencimiento', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20)),
                ('monto', models.FloatField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='appDjango.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='appDjango.tienda'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto_url', models.TextField()),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('minimo_compra', models.IntegerField(default=1)),
                ('unidad', models.CharField(max_length=50)),
                ('activo', models.IntegerField(default=1)),
                ('mayorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='appDjango.mayorista')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='mayorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='appDjango.mayorista'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appDjango.usuario')),
                ('nombre', models.CharField(max_length=255)),
                ('primer_login', models.IntegerField(default=1)),
                ('tipo_perfil', models.CharField(choices=[('general', 'General'), ('especializado', 'Especializado')], default='general', max_length=20)),
                ('activo', models.IntegerField(default=1)),
                ('mayorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='appDjango.mayorista')),
                ('producto_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores_asignados', to='appDjango.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Rendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cobrado', models.FloatField(default=0.0)),
                ('total_comision', models.FloatField(default=0.0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=20)),
                ('mayorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendiciones', to='appDjango.mayorista')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendiciones', to='appDjango.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='appDjango.vendedor'),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appDjango.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_items', to='appDjango.producto')),
            ],
            options={
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
