# Generated by Django 6.0.6 on 2026-06-30 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('bebidas', 'Bebidas'), ('abarrotes', 'Abarrotes'), ('lacteos', 'Lácteos'), ('limpieza', 'Limpieza'), ('otro', 'Otro')], max_length=20)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('activo', 'Activo'), ('suspendido', 'Suspendido')], default='pendiente_pago', max_length=20)),
                ('plan', models.CharField(choices=[('suscripcion', 'Suscripción'), ('comision', 'Comisión'), ('mixto', 'Mixto')], default='suscripcion', max_length=20)),
                ('tarifa_anual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_mayorista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(choices=[('tienda', 'Tienda'), ('vendedor', 'Vendedor')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('digital', 'Digital')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('comision_plataforma', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cobro_confirmado', models.BooleanField(default=False)),
                ('nota_voz_url', models.TextField(blank=True, null=True)),
                ('lat_entrega', models.FloatField(blank=True, null=True)),
                ('lng_entrega', models.FloatField(blank=True, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('mayorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='appDjango.mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='appDjango.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto_url', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('minimo_compra', models.PositiveIntegerField(default=1)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('kg', 'Kilogramo')], default='unidad', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('mayorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='appDjango.mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('direccion_texto', models.TextField(blank=True, null=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tienda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='appDjango.tienda'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('primer_login', models.BooleanField(default=True)),
                ('tipo_perfil', models.CharField(choices=[('general', 'General'), ('especializado', 'Especializado')], default='general', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL)),
                ('mayorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='appDjango.mayorista')),
                ('producto_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores_asignados', to='appDjango.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Rendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado por mayorista')], default='pendiente', max_length=20)),
                ('mayorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendiciones', to='appDjango.mayorista')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendiciones', to='appDjango.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='appDjango.vendedor'),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appDjango.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_items', to='appDjango.producto')),
            ],
            options={
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
