# Generated by Django 6.0.6 on 2026-07-21 12:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlataformaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_suscripcion_anual', models.DecimalField(decimal_places=2, default=Decimal('1200.00'), max_digits=10)),
                ('porcentaje_comision_default', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('tarifa_plan_mixto', models.DecimalField(decimal_places=2, default=Decimal('600.00'), max_digits=10)),
                ('porcentaje_comision_mixto', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='rendicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='appDjango.rendicion'),
        ),
    ]
