# Generated by Django 6.0.6 on 2026-07-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0002_plataformaconfig_pago_rendicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
