# Generated by Django 6.0.6 on 2026-07-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0003_pedido_creado_en_rendicion_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayorista',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
    ]
