# Generated by Django 6.0.6 on 2026-07-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0004_mayorista_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mayorista',
            name='plan',
            field=models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('suscripcion', 'Suscripción anual'), ('comision', 'Solo comisión'), ('mixto', 'Mixto')], default='sin_asignar', max_length=20),
        ),
    ]
